export const ui = {
  pageShell: 'min-h-screen transition-colors duration-300',
  pageLight: 'bg-yellow-50 text-black',
  pageDark: 'bg-zinc-950 text-yellow-100',
  cardLight: 'rounded-lg bg-white shadow-lg border border-yellow-200',
  cardDark: 'rounded-lg bg-zinc-950 shadow-lg border border-yellow-500/20',
  cardSoftLight: 'rounded-xl bg-yellow-50 shadow-md border border-yellow-200',
  cardSoftDark: 'rounded-xl bg-zinc-950 shadow-md border border-yellow-500/20',
  titleLight: 'text-yellow-500',
  titleDark: 'text-yellow-300',
  textMutedLight: 'text-zinc-700',
  textMutedDark: 'text-zinc-300',
  inputLight: 'w-full rounded-md border border-yellow-300 bg-white px-4 py-2 text-black focus:outline-none focus:ring-2 focus:ring-yellow-400',
  inputDark: 'w-full rounded-md border border-yellow-500/40 bg-zinc-950 px-4 py-2 text-yellow-100 focus:outline-none focus:ring-2 focus:ring-yellow-300',
  primaryButton: 'rounded-md bg-yellow-400 px-4 py-2 font-semibold text-black transition duration-300 hover:bg-yellow-300',
  primaryButtonBlock: 'w-full cursor-pointer rounded-md bg-yellow-400 py-2 font-semibold text-black transition duration-300 hover:bg-yellow-300',
  secondaryButtonLight: 'rounded-md bg-black px-4 py-2 text-yellow-100 transition duration-300 hover:bg-zinc-800',
  secondaryButtonDark: 'rounded-md border border-yellow-400 px-4 py-2 text-yellow-200 transition duration-300 hover:bg-yellow-400 hover:text-black',
  linkLight: 'text-yellow-600 hover:underline',
  linkDark: 'text-yellow-300 hover:underline',
  navLight: 'bg-black text-yellow-300 shadow-md',
  navDark: 'bg-yellow-400 text-black shadow-md',
  navActiveLight: 'bg-yellow-400 text-black',
  navHoverLight: 'hover:bg-yellow-300 hover:text-black',
  navActiveDark: 'bg-black text-yellow-300 border border-yellow-300',
  navHoverDark: 'hover:bg-black/80 hover:text-yellow-200',
  alertLight: 'mb-4 rounded border border-yellow-400 bg-yellow-100 px-4 py-3 text-black',
  alertDark: 'mb-4 rounded border border-yellow-500/40 bg-zinc-900 px-4 py-3 text-yellow-100',
};
